#!/usr/bin/ansible-playbook
---
name: User and package management playbook
hosts: all
become: true
gather_facts: true  # Required to determine the OS type

tasks:
  # Task with a list of items (constant iteration)
  - name: Create multiple users and add them to user group
    ansible.builtin.user:
      name: "{{ item }}"
      state: present
      groups: "users"
    loop:
      - myuser1
      - myuser2

  # Package installation task (fixed to use packages instead of users)
  - name: Install packages
    ansible.builtin.package:
      name: "{{ item }}"
      state: present
    loop:
      - httpd
      - curl
    when: ansible_facts['os_family'] == "RedHat"  # Example condition for yum-based systems

  # Task with dictionary items (two variables)
  - name: Create multiple users and add them to different groups
    ansible.builtin.user:
      name: "{{ item.name }}"
      state: present
      groups: "{{ item.groups }}"
    loop:
      - { name: 'myuser3', groups: 'systemd' }
      - { name: 'myuser4', groups: 'games' }
      - { name: 'myuser5', groups: 'games' }
      - { name: 'myuser6', groups: 'systemd' }



