---
- name: User and package management playbook
  hosts: all
  become: true
  gather_facts: true

  tasks:

    - name: Uncreate constant users and unadd them to 'users' group
      ansible.builtin.user:
        name: "{{ item }}"
        state: absent
        groups: users
      loop:
        - constant1
        - constant2

    - name: Uninstall RedHat-specific packages
      ansible.builtin.package:
        name: "{{ item }}"
        state: absent
      loop:
        - httpd
        - nginx
      when: ansible_facts.os_family == "RedHat"

    - name: Uncreate users with specific group assignments
      ansible.builtin.user:
        name: "{{ item.name }}"
        state: absent
        groups: "{{ item.groups }}"
      loop:
        - name: multiple-user3
          groups: michael
        - name: user4
          groups: users
        - name: user5
          groups: users
        - name: user6
          groups: michael
