---
- name: Multi-Block Playbook with Always Sections
  hosts: all
  become: true
  gather_facts: true

  tasks:
    # 🔹 First Block: System Updates
    - name: "BLOCK 1 - System Updates"
      block:
        - name: Update apt cache (Debian/Ubuntu)
          ansible.builtin.apt:
            update_cache: yes
          when: ansible_facts['os_family'] == 'Debian'

        - name: Update yum cache (RHEL/CentOS)
          ansible.builtin.yum:
            name: '*'
            state: latest
          when: ansible_facts['os_family'] == 'RedHat'

      rescue:  # Runs if any task in BLOCK 1 fails
        - name: Notify admin of update failure
          ansible.builtin.debug:
            msg: "System update failed!"

      always:  # Runs REGARDLESS of success/failure
        - name: Log update completion status
          ansible.builtin.debug:
            msg: "Update process completed (successfully or with errors)"

    # 🔹 Second Block: Service Management
    - name: "BLOCK 2 - Service Management"
      block:
        - name: Ensure Nginx is running
          ansible.builtin.service:
            name: nginx
            state: started
            enabled: yes

        - name: Ensure Apache is stopped
          ansible.builtin.service:
            name: httpd
            state: stopped
            enabled: no

      rescue:  # Runs if any task in BLOCK 2 fails
        - name: Log service failure
          ansible.builtin.debug:
            msg: "Failed to manage services!"

      always:  # Runs REGARDLESS of success/failure
        - name: Cleanup temporary files
          ansible.builtin.file:
            path: /tmp/service_setup.tmp
            state: absent

    # 🔹 Third Block: Final Status Report (standalone always example)
    - name: "BLOCK 3 - Final Report"
      block:
        - name: Generate report data
          ansible.builtin.command: echo "System maintenance completed"
          register: report_status
      
      always:  # No rescue, just always
        - name: Deliver final status
          ansible.builtin.debug:
            msg: "Maintenance operation final status: {{ report_status.stdout }}"
