#!/usr/bin/ansible-playbook
---
- name: Manage Nginx Configuration Blocks
  hosts: all
  become: true
  gather_facts: true  # Required to determine the OS type

  tasks:
    - name: Copy nginx.conf to remote machine
      ansible.builtin.copy:
        src: ./folders/nginx.conf
        dest: /etc/nginx/
        mode: '0644'
      delegate_to: localhost
      run_once: true

    - name: Add a new block of text after a marker
      ansible.builtin.blockinfile:
        path: /etc/nginx/nginx.conf
        marker: "# START OF NEW BLOCK"
        block: |
          # New block of text
          location /api {
              proxy_pass http://backend_servers;
              proxy_set_header Host $host;
              proxy_set_header Host2a;
              proxy_set_header Host2b;
          }
      register: block_result

    - name: Print the block insertion result
      ansible.builtin.debug:
        var: block_result

    - name: Replace the block of text if it was changed
      ansible.builtin.blockinfile:
        path: /etc/nginx/nginx.conf
        marker: "# START OF NEW BLOCK"
        block: |
          # Updated block of text
          location /api {
              proxy_pass http://new_backend_servers;
              proxy_set_header Host $host;
              proxy_set_header remote;
              proxy_set_header remote1;
          }
      when: block_result.changed
      #delegate_to: localhost
      #run_once: true

    - name: Remove the block if it was changed
      ansible.builtin.blockinfile:
        path: /etc/nginx/nginx.conf
        marker: "# START OF NEW BLOCK"
        state: absent
      when: block_result.changed

