#!/usr/bin/ansible-playbook
---
- name: Multi-Block Update Sections
  hosts: all
  become: true
  gather_facts: true

  tasks:

    - name: "BLOCK 1 - System Updates"
      block:
        - name: Update apt cache (Debian/Ubuntu)
          ansible.builtin.apt:
            update_cache: yes
          when: ansible_facts['os_family'] == 'Debian'

        - name: Update yum cache (RHEL/CentOS)
          ansible.builtin.yum:
            name: '*'
            state: latest
          when: ansible_facts['os_family'] == 'RedHat'

      rescue:
        - name: Notify admin of update failure
          ansible.builtin.debug:
            msg: "System update failed!"

      always:
        - name: Log update completion status
          ansible.builtin.debug:
            msg: "Update process completed (successfully or with errors)"

# 🔹 Include entire playbooks for service and report sections
- name: Multi-Block Service Management Section
  ansible.builtin.include: include_service_management.yml

- name: Multi-Block Report Section
  ansible.builtin.include: include_reportServer_status.yml

